import type { CategoryDefinition } from '@entities/category';

import type { CardTemplate } from './types';

export const SYSTEM_CATEGORIES: readonly CategoryDefinition[] = Object.freeze([
	{ id: 'sport', title: '运动', sortOrder: 0, enabled: true },
	{ id: 'nutrition', title: '饮食健康', sortOrder: 1, enabled: true },
	{ id: 'learning', title: '学习成长', sortOrder: 2, enabled: true },
	{ id: 'recovery', title: '作息恢复', sortOrder: 3, enabled: true },
	{ id: 'focus', title: '专注自律', sortOrder: 4, enabled: true },
	{ id: 'life-management', title: '生活管理', sortOrder: 5, enabled: true },
]);

export const SYSTEM_CARD_TEMPLATES: readonly CardTemplate[] = Object.freeze([
	{
		id: 'running',
		categoryId: 'sport',
		title: '跑步',
		sortOrder: 0,
		enabled: true,
		version: 1,
		defaultStageMode: 'quantity',
		trackingType: 'quantity',
		iconKey: 'activity',
		accent: 'green',
		defaultDailyTargetBase: 5000,
		stepBase: 500,
		quantity: {
			baseUnit: 'meter',
			displayUnit: 'km',
			basePerDisplayUnit: 1000,
			maxDecimalPlaces: 3,
			confirmationThresholdDisplay: 100,
		},
	},
	{
		id: 'water',
		categoryId: 'nutrition',
		title: '喝水',
		sortOrder: 0,
		enabled: true,
		version: 1,
		defaultStageMode: 'quantity',
		trackingType: 'count',
		iconKey: 'droplet',
		accent: 'cyan',
		defaultDailyTargetBase: 8,
		stepBase: 1,
		quantity: {
			baseUnit: 'cup',
			displayUnit: '杯',
			basePerDisplayUnit: 1,
			maxDecimalPlaces: 0,
			confirmationThresholdDisplay: 30,
		},
	},
	{
		id: 'light-food',
		categoryId: 'nutrition',
		title: '轻食',
		sortOrder: 1,
		enabled: true,
		version: 1,
		defaultStageMode: 'activeDays',
		trackingType: 'checklist',
		iconKey: 'leaf',
		accent: 'green',
		defaultDailyTargetBase: 4,
		stepBase: 1,
		quantity: {
			baseUnit: 'rule',
			displayUnit: '项',
			basePerDisplayUnit: 1,
			maxDecimalPlaces: 0,
			confirmationThresholdDisplay: 20,
		},
	},
	{
		id: 'reading-time',
		categoryId: 'learning',
		title: '阅读',
		sortOrder: 0,
		enabled: true,
		version: 1,
		defaultStageMode: 'quantity',
		trackingType: 'duration',
		iconKey: 'book',
		accent: 'amber',
		defaultDailyTargetBase: 30,
		stepBase: 5,
		quantity: {
			baseUnit: 'minute',
			displayUnit: '分钟',
			basePerDisplayUnit: 1,
			maxDecimalPlaces: 0,
			confirmationThresholdDisplay: 720,
		},
	},
	{
		id: 'sleep',
		categoryId: 'recovery',
		title: '按时睡觉',
		sortOrder: 1,
		enabled: true,
		version: 1,
		defaultStageMode: 'activeDays',
		trackingType: 'check',
		iconKey: 'moon',
		accent: 'violet',
		defaultDailyTargetBase: 1,
		stepBase: 1,
		quantity: {
			baseUnit: 'completion',
			displayUnit: '次',
			basePerDisplayUnit: 1,
			maxDecimalPlaces: 0,
			confirmationThresholdDisplay: 1,
		},
	},
	{
		id: 'screen-free',
		categoryId: 'focus',
		title: '少刷手机',
		sortOrder: 2,
		enabled: true,
		version: 1,
		defaultStageMode: 'activeDays',
		trackingType: 'avoid',
		iconKey: 'shield',
		accent: 'blue',
		defaultDailyTargetBase: 1,
		stepBase: 1,
		quantity: {
			baseUnit: 'completion',
			displayUnit: '天',
			basePerDisplayUnit: 1,
			maxDecimalPlaces: 0,
			confirmationThresholdDisplay: 1,
		},
	},
	{
		id: 'extra-expense',
		categoryId: 'life-management',
		title: '额外开支',
		sortOrder: 0,
		enabled: true,
		version: 1,
		defaultStageMode: 'quantity',
		trackingType: 'quantity',
		iconKey: 'receipt',
		accent: 'amber',
		defaultDailyTargetBase: 100,
		stepBase: 100,
		quantity: {
			baseUnit: 'cent',
			displayUnit: '元',
			basePerDisplayUnit: 100,
			maxDecimalPlaces: 2,
			confirmationThresholdDisplay: 1_000_000,
		},
	},
]);
